### ISSUE TITLE
Cannot compile in Ubuntu 14.04 with pypy 5.0.1

### ISSUE THREAD

**Issue by acardona** [mattip/matplotlib#2]
When compiling matplotlib, I get the following error in ubuntu 14.04 and pypy 5.0.1. Would appreciate hints as to whether the error is because of lack of installed libraries in my system. Prior to attempting the installation of matplotlib in pypy, I installed pypy and pypy-dev, as well as numpy in the recommended way for pypy (and tested that it works).

~/python/pypy/matplotlib (master)$ workon pypy
(pypy) ~/python/pypy/matplotlib (master)$ pypy setup.py install
============================================================================
Edit setup.cfg to change the build options

BUILDING MATPLOTLIB
            matplotlib: yes [1.4.x]
                python: yes [2.7.10 (5.0.1+dfsg-4~ppa1~ubuntu14.04.1, Apr 10
                        2016, 06:29:21) [PyPy 5.0.1 with GCC 4.8.4]]
              platform: yes [linux2]

REQUIRED DEPENDENCIES AND EXTENSIONS
                 numpy: yes [version 1.10.0]
              dateutil: yes [dateutil was not found. It is required for date
                        axis support. pip/easy_install may attempt to
                        install it after matplotlib.]
               tornado: yes [tornado was not found. It is required for the
                        WebAgg backend. pip/easy_install may attempt to
                        install it after matplotlib.]
             pyparsing: yes [pyparsing was not found. It is required for
                        mathtext support. pip/easy_install may attempt to
                        install it after matplotlib.]
                 pycxx: yes [Couldn't import.  Using local copy.]
                libagg: yes [pkg-config information for 'libagg' could not
                        be found. Using local copy.]
              freetype: yes [version 17.1.11]
                   png: yes [version 1.2.50]

OPTIONAL SUBPACKAGES
           sample_data: yes [installing]
              toolkits: yes [installing]
                 tests: yes [nose 0.11.1 or later is required to run the
                        matplotlib test suite]

OPTIONAL BACKEND EXTENSIONS
                macosx: no  [Mac OS-X only]
                qt4agg: no  [PyQt4 not found]
               gtk3agg: no  [Requires pygobject to be installed.]
             gtk3cairo: no  [Requires cairo to be installed.]
                gtkagg: no  [Requires pygtk]
                 tkagg: no  [TKAgg requires Tkinter.]
                 wxagg: no  [requires wxPython]
                   gtk: no  [Requires pygtk]
                   agg: yes [installing]
                 cairo: no  [cairo not found]
             windowing: no  [Microsoft Windows only]

OPTIONAL LATEX DEPENDENCIES
                dvipng: yes [version 1.14]
           ghostscript: yes [version 9.10]
                 latex: yes [version 3.1415926]
               pdftops: yes [version 0.24.5]

running install
Checking .pth file support in /home/albert/.virtualenvs/pypy/site-packages/
/home/albert/.virtualenvs/pypy/bin/pypy -E -c pass
TEST PASSED: /home/albert/.virtualenvs/pypy/site-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing top-level names to lib/matplotlib.egg-info/top_level.txt
writing lib/matplotlib.egg-info/PKG-INFO
writing requirements to lib/matplotlib.egg-info/requires.txt
writing namespace_packages to lib/matplotlib.egg-info/namespace_packages.txt
writing dependency_links to lib/matplotlib.egg-info/dependency_links.txt
reading manifest file 'lib/matplotlib.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'lib/matplotlib.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying lib/matplotlib/mpl-data/matplotlibrc -> build/lib.linux-x86_64-2.7/matplotlib/mpl-data
running build_ext
building 'matplotlib._png' extension
cc -O2 -fPIC -Wimplicit -DPY_ARRAY_UNIQUE_SYMBOL=MPL_matplotlib__png_ARRAY_API -DPYCXX_ISO_CPP_LIB=1 -I/usr/local/include -I/usr/include -I. -I/usr/include/libpng12 -I/home/albert/.virtualenvs/pypy/site-packages/numpy/core/include -I/home/albert/.virtualenvs/pypy/include -c src/_png.cpp -o build/temp.linux-x86_64-2.7/src/_png.o
cc1plus: warning: command line option ‘-Wimplicit’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from /home/albert/.virtualenvs/pypy/site-packages/numpy/core/include/numpy/ndarraytypes.h:1781:0,
                 from /home/albert/.virtualenvs/pypy/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/albert/.virtualenvs/pypy/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from src/_png.cpp:28:
/home/albert/.virtualenvs/pypy/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from src/file_compat.h:4:0,
                 from src/_png.cpp:31:
/home/albert/.virtualenvs/pypy/site-packages/numpy/core/include/numpy/npy_3kcompat.h: In function ‘void PyUnicode_ConcatAndDel(PyObject**, PyObject*)’:
/home/albert/.virtualenvs/pypy/site-packages/numpy/core/include/numpy/npy_3kcompat.h:125:43: error: ‘PyUnicode_Concat’ was not declared in this scope
     newobj = PyUnicode_Concat(*left, right);
                                           ^
/home/albert/.virtualenvs/pypy/site-packages/numpy/core/include/numpy/npy_3kcompat.h: In function ‘void PyUnicode_Concat2(PyObject**, PyObject*)’:
/home/albert/.virtualenvs/pypy/site-packages/numpy/core/include/numpy/npy_3kcompat.h:135:43: error: ‘PyUnicode_Concat’ was not declared in this scope
     newobj = PyUnicode_Concat(*left, right);
                                           ^
src/_png.cpp: In function ‘PyObject* write_png(PyObject*, PyObject*)’:
src/_png.cpp:150:51: error: ‘npy_PyFile_Dup’ was not declared in this scope
     if ((fp = npy_PyFile_Dup(py_file, (char *)"wb")))
                                                   ^
src/_png.cpp:246:48: error: ‘npy_PyFile_DupClose’ was not declared in this scope
             if (npy_PyFile_DupClose(py_file, fp)) {
                                                ^
src/_png.cpp:267:44: error: ‘npy_PyFile_DupClose’ was not declared in this scope
         if (npy_PyFile_DupClose(py_file, fp)) {
                                            ^
src/_png.cpp: In function ‘PyObject* _read_png(const Py::Object&, bool, int)’:
src/_png.cpp:336:43: error: ‘npy_PyFile_Dup’ was not declared in this scope
     if ((fp = npy_PyFile_Dup(py_file, "rb")))
                                           ^
src/_png.cpp:594:44: error: ‘npy_PyFile_DupClose’ was not declared in this scope
         if (npy_PyFile_DupClose(py_file, fp)) {
                                            ^
error: command 'cc' failed with exit status 1

**Comment by mattip** [comment]
Should be fixed now, the problem was in `pypy/numpy`. Delete `<pypy>/site-packages/numpy`, update, and reinstall it. 
Thanks for the report

**Comment by acardona** [comment]
Thank you! compiled!

For the record:
$ workon pypy
$ pip uninstall numpy
$ cd numpy
$ git pull
$ pypy setup.py install
$ cd .../matplotlib
$ pypy setup.py install

Now both numpy and matplotlib can be imported into a pypy script.
